[build]
  base = "client"  # This specifies the base directory for the build
  command = "npm run build"  # This will run the build command from client/package.json
  publish = ".next"  # This is where the built output is located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
